# $ kustomize build k8s/dev | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - config.yaml
secretGenerator:
  - name: mysql-config
    behavior: merge
    envs:
      - application.env