apiVersion: builtin
kind: PatchTransformer
metadata:
  name: set-volumes
target:
  group: apps
  version: v1
  kind: Deployment
  matchLabels:
    services: mysql
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: irrelevant
  spec:
    template:
      spec:
        containers:
        - name: app
          volumeMounts:
          - name: mysql
            mountPath: /config/bindings/mysql
          env:
          - name: SERVICE_BINDING_ROOT
            value: /config/bindings
          - name: MYSQL_HOST
            value: $(MYSQL_HOST)
        volumes:
        - name: mysql
          secret:
            secretName: mysql-config
