# $ kustomize build k8s/dev | kubectl apply -f -
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app.yaml
vars:
  - name: MYSQL_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: mysql