apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- mysql.yaml
resources:
- ../../base
- ../../mysql
namePrefix: petclinic-
# You can either include ../../mysql or use commonLabels here, but not both, 
# otherwise the app service selects the mysql pods
# commonLabels:
#   app: petclinic
transformers:
- ../../mysql/transformer
- ../../actuator
images:
  - name: dsyer/template
    newName: springio/petclinic
vars:
  - name: MYSQL_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: mysql
